version: "3.7"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  redis:
    << : *restart_policy
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

    command:
      --save 60 1

    volumes:
      - /docker/host/monty-redis:/data

  monty-python:
    << : *restart_policy
    image: ghcr.io/onerandomusername/monty-python:latest
    container_name: monty-python
    init: true
    tty: true

    depends_on:
      - redis

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
