[tool.poetry]
name = "monty"
version = "1.0.0"
description = "Helpful bot for python, github, and discord things."
authors = ["aru <genericusername414@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~=3.9"
aiodns = "~=2.0"
aiohttp = "~=3.8.1"
aioredis = "~1.3"
arrow = "~=1.2.2"
async-rediscache = {extras = ["fakeredis"], version = "~=0.1.4"}
colorama = { version = "~=0.4.3", markers = "sys_platform == 'win32'" }
coloredlogs = "~=14.0"
disnake = {git = "https://github.com/DisnakeDev/disnake.git", rev='master'}
emoji = "~=1.7.0"
feedparser = "~=6.0.2"
rapidfuzz = "~=1.4"
python-dateutil = "~=2.8"
python-frontmatter = "~=1.0.0"
beautifulsoup4 = "^4.10.0"
markdownify = "==0.11.2"
lxml = "^4.6.4"
Pillow = "^9.0.0"
psutil = "^5.9.0"
base65536 = "^0.1.1"
statsd = "^3.3.0"


[tool.poetry.dev-dependencies]
black = "^22.0"
coverage = "~=5.0"
flake8 = "^4.0"
flake8-annotations = "~=2.9.0"
flake8-bugbear = "~=22.4.0"
flake8-docstrings = "~=1.6"
flake8-isort = "^4.0.0"
flake8-string-format = "~=0.3"
flake8-tidy-imports = "~=4.1"
flake8-todo = "~=0.7"
isort = "^5.10.1"
pre-commit = "~=2.18.0"
taskipy = "~=1.10.0"
python-dotenv = "~=0.20.0"
pytest = "~=6.2.4"
pytest-cov = "~=2.12.1"
pytest-xdist = { version = "~=2.3.0", extras = ["psutil"] }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'

[tool.taskipy.tasks]
export = 'poetry export --without-hashes -o requirements.txt'
start = "python -m monty"
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
test-nocov = "pytest -n auto"
test = "pytest -n auto --cov-report= --cov"
html = "coverage html"
report = "coverage report"

[tool.coverage.run]
branch = true
source_pkgs = ["bot"]
source = ["tests"]
