[meta]

[schema.prefix]
name = 'Command Prefix'
description = 'The prefix for prefix commands'
require_bot = true
success_message = 'Successfully set the prefix to `{new}`.'
show_message = 'The currently set prefix is `{current}`.'
null_show_message = 'There is currently no set prefix.'
nullable = true
success_clear_message = 'Successfully cleared the prefix. Now using the default prefix.'
validation_error_message = 'The prefix must be at least '

[schema.github_issues_org]
name = 'Github Issues Organisation'
description = 'The organisation or user to default repository search to.'
require_bot = true
success_message = 'Successfully set the github org to `{new}`.'
show_message = 'The currently set github org is `{current}`.'
null_show_message = 'There is currently no set github org.'
nullable = true
success_clear_message = 'Successfully cleared the configured github organsation.'
validation_error_message = 'This must be a valid organisation or user!'
